---
apiVersion: v1
kind: Service
metadata:
  name: admission-webhook
  namespace: kube-admission
  labels:
    app.kubernetes.io/name: admission-webhook
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8443
  selector:
    app.kubernetes.io/name: admission-webhook
